[package]
name = "firewall_reentrancy_detect"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy={version="0.4.2",features=["full","provider-debug-api"]}
futures="0.3.31"
tokio = { version = "1.40.0", features = ["full"] }
lazy_static = "1.5.0"